#!/usr/bin/env python3
"""Generate the small 16x16 bitmap font ROM used by the FPGA OSD."""

from pathlib import Path
from PIL import Image, ImageDraw, ImageFont


GLYPHS = [
    " ", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", ":", "E",
    "校", "园", "赛", "事", "信", "息", "轮", "播", "准", "备", "倒", "计", "时",
    "开", "始", "进", "行", "中", "暂", "停", "继", "续", "结", "束", "米", "跳",
    "绳", "篮", "球", "投", "趣", "味", "接", "力", "项", "目", "卡", "未", "插",
    "入", "初", "化", "失", "败", "无", "图", "片", "读", "取", "连", "错", "误",
    "请", "检", "查", "返", "回", "比", "x",
    "设", "置", "音", "量", "亮", "度", "对", "锐", "转"
]


def find_font() -> Path:
    candidates = [
        Path(r"C:\Windows\Fonts\msyh.ttc"),
        Path(r"C:\Windows\Fonts\simhei.ttf"),
        Path(r"C:\Windows\Fonts\simsun.ttc"),
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    raise FileNotFoundError("No Microsoft YaHei, SimHei, or SimSun font was found")


def glyph_rows(font: ImageFont.FreeTypeFont, char: str) -> list[int]:
    image = Image.new("1", (16, 16), 0)
    draw = ImageDraw.Draw(image)
    box = draw.textbbox((0, 0), char, font=font)
    width = box[2] - box[0]
    height = box[3] - box[1]
    x = (16 - width) // 2 - box[0]
    y = (16 - height) // 2 - box[1]
    draw.text((x, y), char, font=font, fill=1)
    rows = []
    for row in range(16):
        value = 0
        for col in range(16):
            if image.getpixel((col, row)):
                value |= 1 << (15 - col)
        rows.append(value)
    return rows


def main() -> None:
    script_dir = Path(__file__).resolve().parent
    output = script_dir / "saixian_font_rom.v"
    font_path = find_font()
    font = ImageFont.truetype(str(font_path), 15)

    lines = [
        "// Generated by doc/tools/generate_font_rom.py. Do not edit manually.",
        "module saixian_font_rom(",
        "    input  wire [6:0] glyph_id,",
        "    input  wire [3:0] row,",
        "    output reg  [15:0] bits",
        ");",
        "always @* begin",
        "    bits = 16'h0000;",
        "    case ({glyph_id, row})",
    ]
    for glyph_id, char in enumerate(GLYPHS):
        for row, value in enumerate(glyph_rows(font, char)):
            if value:
                lines.append(
                    f"        11'h{(glyph_id << 4) | row:03X}: bits = 16'h{value:04X};"
                )
    lines.extend([
        "        default: bits = 16'h0000;",
        "    endcase",
        "end",
        "endmodule",
        "",
    ])
    output.write_text("\n".join(lines), encoding="utf-8")
    print(f"generated {output} with {len(GLYPHS)} glyphs from {font_path}")


if __name__ == "__main__":
    main()
